# Generated by Django 5.1 on 2024-09-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_feedback_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='enrollment_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='student',
        ),
    ]
