# Generated by Django 5.1 on 2024-09-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_enrolled_at_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_date',
            new_name='enrolled_at',
        ),
    ]
