# Generated by Django 5.1.1 on 2024-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
