# Generated by Django 5.1.1 on 2024-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_delete_teacher_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, default='course_videos/default.mp4', null=True, upload_to='course_videos/'),
        ),
    ]
